package i5.las2peer.services.noracleQuestionService;


import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import com.fasterxml.jackson.core.JsonProcessingException;

import i5.las2peer.api.Service;
import i5.las2peer.api.Context;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;
 

/**
 *
 * Noracle-Question-Service
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("rmi/noraclequestionservice/question")
public class NoracleQuestionService extends RESTService {





  public NoracleQuestionService() {
	super();
    // read and set properties values
    setFieldValues();

  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "Noracle-Question-Service", version = "1.0",
          description = "A las2peer microservice generated by the CAE.",
          termsOfService = "none",
          contact = @Contact(name = "", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/CAE-Community-Application-Editor/microservice-Noracle-Question-Service/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final NoracleQuestionService service = (NoracleQuestionService) Context.getCurrent().getService();

      /**
   * 
   * createQuestion
   * 
   * @param questionSpaceId a String 
   * @param questionText a String 
   * 
   * @return Response  
   * 
   */
  @POST
  @Path("/ ")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "msg")
  })
  @ApiOperation(value = "createQuestion", notes = " ")
  public Response createQuestion(@PathParam("questionSpaceId") String questionSpaceId, @PathParam("questionText") String questionText) {

    // msg
    boolean msg_condition = true;
    if(msg_condition) {
      JSONObject QuestionCreatedResponseEntity = new JSONObject();
      return Response.status(HttpURLConnection.HTTP_OK).entity(QuestionCreatedResponseEntity.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * getQuestion
   * 
   * @param questionid a String 
   * 
   * @return Response  
   * 
   */
  @GET
  @Path("//{questionid}")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "question")
  })
  @ApiOperation(value = "getQuestion", notes = " ")
  public Response getQuestion(@PathParam("questionid") String questionid) {

    // question
    boolean question_condition = true;
    if(question_condition) {
      JSONObject QuestionGetResponseEntity = new JSONObject();
      return Response.status(HttpURLConnection.HTTP_OK).entity(QuestionGetResponseEntity.toJSONString()).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

}
